version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_StYVO2uKad6Q@ep-bold-thunder-a2v1armx-pooler.eu-central-1.aws.neon.tech/neondb?sslmode=require
      SECRET_KEY_BASE: 0d78202ead5103319851a09a93dbc6d6bc3ff08c55e5e2278ac3c44eda4c311380e7e4873f362a26111846aefc62ceb4f29bc6a6faf25a683e5f3305fa8b7483
    networks:
      - appnet

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_StYVO2uKad6Q
      POSTGRES_DB: neondb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge
